server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/identity_service
     username: postgres
     password: 1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
